python3 sueca.py -o results/random_greedy -s random -b greedy -n 10000 > results/random_greedy.txt
python3 sueca.py -o results/random_maxpointswon -s random -b maxpointswon -n 10000 > results/random_maxpointswon.txt
python3 sueca.py -o results/random_maxroundswon -s random -b maxroundswon -n 10000 > results/random_maxroundswon.txt
python3 sueca.py -o results/random_cooperative -s random -b cooperative -n 10000 > results/random_cooperative.txt
python3 sueca.py -o results/random_predictor -s random -b predictor -n 10000 > results/random_predictor.txt
python3 sueca.py -o results/greedy_maxpointswon -s greedy -b maxpointswon -n 10000 > results/greedy_maxpointswon.txt
python3 sueca.py -o results/greedy_maxroundswon -s greedy -b maxroundswon -n 10000 > results/greedy_maxroundswon.txt
python3 sueca.py -o results/greedy_cooperative -s greedy -b cooperative -n 10000 > results/greedy_cooperative.txt
python3 sueca.py -o results/greedy_predictor -s greedy -b predictor -n 10000 > results/greedy_predictor.txt
python3 sueca.py -o results/maxpointswon_maxroundswon -s maxpointswon -b maxroundswon -n 10000 > results/maxpointswon_maxroundswon.txt
python3 sueca.py -o results/maxpointswon_cooperative -s maxpointswon -b cooperative -n 10000 > results/maxpointswon_cooperative.txt
python3 sueca.py -o results/maxpointswon_predictor -s maxpointswon -b predictor -n 10000 > results/maxpointswon_predictor.txt
python3 sueca.py -o results/maxroundswon_cooperative -s maxroundswon -b cooperative -n 10000 > results/maxroundswon_cooperative.txt
python3 sueca.py -o results/maxroundswon_predictor -s maxroundswon -b predictor -n 10000 > results/maxroundswon_predictor.txt
python3 sueca.py -o results/cooperative_predictor -s cooperative -b predictor -n 10000 > results/cooperative_predictor.txt
