python3 sueca.py -o results/random_greedy.json -s random -b greedy -n 10000 > results/random_greedy.txt
python3 sueca.py -o results/random_maxpointswon.json -s random -b maxpointswon -n 10000 > results/random_maxpointswon.txt
python3 sueca.py -o results/random_maxroundswon.json -s random -b maxroundswon -n 10000 > results/random_maxroundswon.txt
python3 sueca.py -o results/random_cooperative.json -s random -b cooperative -n 10000 > results/random_cooperative.txt
python3 sueca.py -o results/random_predictor.json -s random -b predictor -n 10000 > results/random_predictor.txt
python3 sueca.py -o results/greedy_maxpointswon.json -s greedy -b maxpointswon -n 10000 > results/greedy_maxpointswon.txt
python3 sueca.py -o results/greedy_maxroundswon.json -s greedy -b maxroundswon -n 10000 > results/greedy_maxroundswon.txt
python3 sueca.py -o results/greedy_cooperative.json -s greedy -b cooperative -n 10000 > results/greedy_cooperative.txt
python3 sueca.py -o results/greedy_predictor.json -s greedy -b predictor -n 10000 > results/greedy_predictor.txt
python3 sueca.py -o results/maxpointswon_maxroundswon.json -s maxpointswon -b maxroundswon -n 10000 > results/maxpointswon_maxroundswon.txt
python3 sueca.py -o results/maxpointswon_cooperative.json -s maxpointswon -b cooperative -n 10000 > results/maxpointswon_cooperative.txt
python3 sueca.py -o results/maxpointswon_predictor.json -s maxpointswon -b predictor -n 10000 > results/maxpointswon_predictor.txt
python3 sueca.py -o results/maxroundswon_cooperative.json -s maxroundswon -b cooperative -n 10000 > results/maxroundswon_cooperative.txt
python3 sueca.py -o results/maxroundswon_predictor.json -s maxroundswon -b predictor -n 10000 > results/maxroundswon_predictor.txt
python3 sueca.py -o results/cooperative_predictor.json -s cooperative -b predictor -n 10000 > results/cooperative_predictor.txt
