python3 sueca.py -o random_greedy -s random -b greedy -n 10000
python3 sueca.py -o random_maxpointswon -s random -b maxpointswon -n 10000
python3 sueca.py -o random_maxroundswon -s random -b maxroundswon -n 10000
python3 sueca.py -o random_cooperative -s random -b cooperative -n 10000
python3 sueca.py -o random_predictor -s random -b predictor -n 10000
python3 sueca.py -o greedy_maxpointswon -s greedy -b maxpointswon -n 10000
python3 sueca.py -o greedy_maxroundswon -s greedy -b maxroundswon -n 10000
python3 sueca.py -o greedy_cooperative -s greedy -b cooperative -n 10000
python3 sueca.py -o greedy_predictor -s greedy -b predictor -n 10000
python3 sueca.py -o maxpointswon_maxroundswon -s maxpointswon -b maxroundswon -n 10000
python3 sueca.py -o maxpointswon_cooperative -s maxpointswon -b cooperative -n 10000
python3 sueca.py -o maxpointswon_predictor -s maxpointswon -b predictor -n 10000
python3 sueca.py -o maxroundswon_cooperative -s maxroundswon -b cooperative -n 10000
python3 sueca.py -o maxroundswon_predictor -s maxroundswon -b predictor -n 10000
python3 sueca.py -o cooperative_predictor -s cooperative -b predictor -n 10000